### ISSUE TITLE
Error from server: 412 - Precondition Failed

### ISSUE THREAD

**Issue by ibuckshot5** [dracoapi/nodedracoapi#1]
Developing a Draconius GO scanner, and was creating some accounts. Got this error on `/examples/createUser.js`

`{ Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\Users\ibuckshot\nodedracoapi\bin\index.js:132:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  details: FServiceError { __type: 'FServiceError', args: [], cause: 'AUTH_ERROR' } }`

Full log:

`Starting...
Boot...
Init login...
Generate nickname...
  nickname: jgtbaotz
Accept tos...
Register account...
{ Error: Error from server: 412 - Precondition Failed
    at Client.call (C:\Users\ibuckshot\nodedracoapi\bin\index.js:132:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  details: FServiceError { __type: 'FServiceError', args: [], cause: 'AUTH_ERROR' } }`

**Comment by snooter** [comment]
User accounts now require linking a Facebook or Google account, so this doesn't work anymore. :-(

**Comment by niicojs** [comment]
yes, creating device account has now been blocked
